AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  CDPlutoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: 'A starter AWS Lambda function for Project Pluto'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::787879518159:role/Lambda_EC2_Read
      Events:
          getAZsAPI:
              Type: Api 
              Properties:
                  Path: /getazs
                  Method: get
      Environment:
        Variables:
          REGION: us-east-1        